### ISSUE TITLE
Deprecation warnings after DataStructures update

### ISSUE THREAD

**Issue by pbayer** [BenLauwens/SimJulia.jl#36] opened 2017-09-05 08:25 UTC
Hi Ben,

I get the following (nasty) deprecation warnings when working with SimJulia:

`WARNING: PriorityQueue{K, V}(::Type{K}, ::Type{V}) is deprecated, use PriorityQueue{K, V}() instead.`

`Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] DataStructures.PriorityQueue(::Type{SimJulia.Put}, ::Type{SimJulia.ContainerKey{Int64}}) at ./deprecated.jl:57
 [3] Type at /Users/paul/.julia/v0.6/SimJulia/src/resources/containers.jl:15 [inlined]
 [4] #Resource#36 at /Users/paul/.julia/v0.6/SimJulia/src/resources/containers.jl:26 [inlined]
 [5] Type at /Users/paul/.julia/v0.6/SimJulia/src/resources/containers.jl:26 [inlined]
 [6] workunit(::SimJulia.Simulation, ::Int64, ::String, ::String, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /Users/paul/.julia/v0.6/PFlow/src/activities.jl:185
 [7] readWorkunits(::String, ::SimJulia.Simulation) at /Users/paul/.julia/v0.6/PFlow/src/io.jl:20`

This happens when I call `Resource(sim, 1)`

Thanks,
Paul

**Comment by BenLauwens** [comment] 2017-09-05 21:09
Hi Paul

I will look at this.
Kind regards

Ben

**Comment by BenLauwens** [comment] 2017-09-06 09:51
Hi Paul

The problem is solved in the `master` branch but I have put the `@resumable` and the `@yield` macros in a separate package `ResumableFunctions` and I have to wait for the release v0.1.1 to become available in the package repository to release a new version of `SimJulia`. In the mean time you can install and checkout manually the new version of `ResumableFunctions` and checkout the master branch of `SimJulia`:
```julia
Pkg.install("ResumableFunctions")
Pkg.checkout("ResumableFunctions", "v0.1.1")
Pkg.checkout("SimJulia")
```
I leave this issue open until `SimJulia` v0.4.1. is released with the bugs fixed.

Kind regards

Ben

**Comment by pbayer** [comment] 2017-09-07 05:18
Hi Ben,
Thank you,
Paul

**Comment by BenLauwens** [comment] 2017-09-08 20:32
Hi Paul

Simjulia v0.4.1 has just been released. The deprecation warnings are fixed!
Kind regards. 

Ben

**Closed by BenLauwens** 2017-09-08 20:32 UTC
